export interface LegalDocument {
  id: string;
  title: string;
  category: string;
  article: string;
  content: string;
  keywords: string[];
  source: string;
}

export const SEED_DOCUMENTS: LegalDocument[] = [
  {
    id: 'ce-1',
    title: 'Constitución Española',
    category: 'constitucional',
    article: 'Artículo 14',
    content: 'Los españoles son iguales ante la ley, sin que pueda prevalecer discriminación alguna por razón de nacimiento, raza, sexo, religión, opinión o cualquier otra condición o circunstancia personal o social.',
    keywords: ['igualdad', 'discriminación', 'derechos', 'igualdad ante la ley'],
    source: 'Constitución Española, Artículo 14',
  },
  {
    id: 'ce-2',
    title: 'Constitución Española',
    category: 'constitucional',
    article: 'Artículo 18',
    content: 'Se garantiza el derecho al honor, a la intimidad personal y familiar y a la propia imagen. El domicilio es inviolable. Ninguna entrada o registro podrá hacerse en él sin consentimiento del titular o resolución judicial, salvo en caso de flagrante delito. Se garantiza el secreto de las comunicaciones y, en especial, de las postales, telegráficas y telefónicas, salvo resolución judicial.',
    keywords: ['honor', 'intimidad', 'domicilio', 'inviolabilidad', 'secreto comunicaciones', 'privacidad'],
    source: 'Constitución Española, Artículo 18',
  },
  {
    id: 'ce-3',
    title: 'Constitución Española',
    category: 'constitucional',
    article: 'Artículo 24',
    content: 'Todas las personas tienen derecho a obtener la tutela efectiva de los jueces y tribunales en el ejercicio de sus derechos e intereses legítimos, sin que, en ningún caso, pueda producirse indefensión. Asimismo, todos tienen derecho al Juez ordinario predeterminado por la ley, a la defensa y a la asistencia de letrado, a ser informados de la acusación formulada contra ellos, a un proceso público sin dilaciones indebidas y con todas las garantías, a utilizar los medios de prueba pertinentes para su defensa, a no declarar contra sí mismos, a no confesarse culpables y a la presunción de inocencia.',
    keywords: ['tutela judicial', 'defensa', 'abogado', 'proceso', 'presunción inocencia', 'juicio'],
    source: 'Constitución Española, Artículo 24',
  },
  {
    id: 'ce-4',
    title: 'Constitución Española',
    category: 'constitucional',
    article: 'Artículo 25',
    content: 'Nadie puede ser condenado o sancionado por acciones u omisiones que en el momento de producirse no constituyan delito, falta o infracción administrativa, según la legislación vigente en aquel momento. Las penas privativas de libertad y las medidas de seguridad estarán orientadas hacia la reeducación y reinserción social.',
    keywords: ['pena', 'condena', 'delito', 'sanción', 'legalidad penal', 'reinserción'],
    source: 'Constitución Española, Artículo 25',
  },
  {
    id: 'ce-5',
    title: 'Constitución Española',
    category: 'constitucional',
    article: 'Artículo 33',
    content: 'Se reconoce el derecho a la propiedad privada y a la herencia. La función social de estos derechos delimitará su contenido, de acuerdo con las leyes. Nadie podrá ser privado de sus bienes y derechos sino por causa justificada de utilidad pública o interés social, mediante la correspondiente indemnización y de conformidad con lo dispuesto por las leyes.',
    keywords: ['propiedad', 'herencia', 'expropiación', 'indemnización', 'bienes'],
    source: 'Constitución Española, Artículo 33',
  },
  {
    id: 'ce-6',
    title: 'Constitución Española',
    category: 'constitucional',
    article: 'Artículo 35',
    content: 'Todos los españoles tienen el deber de trabajar y el derecho al trabajo, a la libre elección de profesión u oficio, a la promoción a través del trabajo y a una remuneración suficiente para satisfacer sus necesidades y las de su familia, sin que en ningún caso pueda hacerse discriminación por razón de sexo.',
    keywords: ['trabajo', 'trabajador', 'empleo', 'salario', 'remuneración', 'profesión'],
    source: 'Constitución Española, Artículo 35',
  },
  {
    id: 'cc-1',
    title: 'Código Civil',
    category: 'civil',
    article: 'Artículo 108',
    content: 'La obligación se extingue por el pago o cumplimiento, por la pérdida de la cosa debida, por el condonación de la deuda, por la confusión de los derechos de acreedor y deudor, por la compensación y por la novación.',
    keywords: ['obligación', 'deuda', 'pago', 'cumplimiento', 'contrato'],
    source: 'Código Civil, Artículo 108',
  },
  {
    id: 'cc-2',
    title: 'Código Civil',
    category: 'civil',
    article: 'Artículo 109',
    content: 'El deudor debe cumplir la obligación en los términos en que fue contraída, y es responsable de los daños y perjuicios derivados del incumplimiento, salvo que concurra causa de fuerza mayor.',
    keywords: ['deudor', 'incumplimiento', 'daños', 'perjuicios', 'responsabilidad contractual'],
    source: 'Código Civil, Artículo 109',
  },
  {
    id: 'cc-3',
    title: 'Código Civil',
    category: 'civil',
    article: 'Artículo 1902',
    content: 'El que por acción u omisión causa daño a otro, interviniendo culpa o negligencia, está obligado a reparar el daño causado.',
    keywords: ['responsabilidad civil', 'daño', 'negligencia', 'culpa', 'indemnización'],
    source: 'Código Civil, Artículo 1902',
  },
  {
    id: 'cc-4',
    title: 'Código Civil',
    category: 'civil',
    article: 'Artículo 1964',
    content: 'Las acciones personales que no tengan plazo especial prescriben a los cinco años desde que pueda exigirse el cumplimiento de la obligación.',
    keywords: ['prescripción', 'plazo', 'acción personal', 'obligación'],
    source: 'Código Civil, Artículo 1964',
  },
  {
    id: 'cp-1',
    title: 'Código Penal',
    category: 'penal',
    article: 'Artículo 138',
    content: 'El que matare a otro será castigado, como reo de homicidio, con la pena de prisión de diez a quince años.',
    keywords: ['homicidio', 'muerte', 'prisión', 'pena'],
    source: 'Código Penal, Artículo 138',
  },
  {
    id: 'cp-2',
    title: 'Código Penal',
    category: 'penal',
    article: 'Artículo 147',
    content: 'El que, por cualquier medio o procedimiento, causare a otro una lesión que menoscabe su integridad corporal o su salud física o mental, será castigado con la pena de prisión de tres meses a tres años o multa de seis a doce meses.',
    keywords: ['lesiones', 'integridad física', 'salud', 'violencia'],
    source: 'Código Penal, Artículo 147',
  },
  {
    id: 'cp-3',
    title: 'Código Penal',
    category: 'penal',
    article: 'Artículo 237',
    content: 'Son reos del delito de robo los que, con ánimo de lucrarse, se apoderaren de las cosas muebles ajenas empleando fuerza en las cosas para acceder al lugar donde se encuentran o violencia o intimidación en las personas.',
    keywords: ['robo', 'hurto', 'violencia', 'intimidación', 'apoderamiento'],
    source: 'Código Penal, Artículo 237',
  },
  {
    id: 'cp-4',
    title: 'Código Penal',
    category: 'penal',
    article: 'Artículo 248',
    content: 'Cometen estafa los que, con ánimo de lucro, utilizaren engaño bastante para producir error en otro, induciéndolo a realizar un acto de disposición en perjuicio propio o ajeno.',
    keywords: ['estafa', 'engaño', 'fraude', 'lucro'],
    source: 'Código Penal, Artículo 248',
  },
  {
    id: 'et-1',
    title: 'Estatuto de los Trabajadores',
    category: 'laboral',
    article: 'Artículo 4',
    content: 'Los trabajadores tienen como derechos básicos: trabajo y libre elección de profesión, libre sindicación, negociación colectiva, huelga, reunión, información y formación profesional, no discriminación para el empleo, integridad física y protección frente al acoso.',
    keywords: ['trabajador', 'derechos laborales', 'sindicato', 'huelga', 'formación'],
    source: 'Estatuto de los Trabajadores, Artículo 4',
  },
  {
    id: 'et-2',
    title: 'Estatuto de los Trabajadores',
    category: 'laboral',
    article: 'Artículo 14',
    content: 'El período de prueba tendrá una duración máxima de seis meses para los técnicos titulados, y de dos meses para los demás trabajadores, pudiendo establecerse por convenio colectivo duraciones distintas.',
    keywords: [' período de prueba', 'contrato', 'técnico', 'trabajador'],
    source: 'Estatuto de los Trabajadores, Artículo 14',
  },
  {
    id: 'et-3',
    title: 'Estatuto de los Trabajadores',
    category: 'laboral',
    article: 'Artículo 33',
    content: 'El Fondo de Garantía Salarial (FOGASA) abonará a los trabajadores el importe de los salarios pendientes de pago por causa de insolvencia o concurso del empresario, con el límite de 150 días y el doble del SMI.',
    keywords: ['FOGASA', 'salario', 'insolvencia', 'concurso', 'garantía salarial', 'despido'],
    source: 'Estatuto de los Trabajadores, Artículo 33',
  },
  {
    id: 'et-4',
    title: 'Estatuto de los Trabajadores',
    category: 'laboral',
    article: 'Artículo 49',
    content: 'El contrato de trabajo se extingue por mutuo acuerdo, causas consignadas en el contrato, expiración del tiempo convenido, dimisión del trabajador, muerte del trabajador o empresario, jubilación, despido disciplinario, despido por causas objetivas, despido colectivo y fuerza mayor.',
    keywords: ['extinción contrato', 'despido', 'dimisión', 'baja', 'fin relación laboral'],
    source: 'Estatuto de los Trabajadores, Artículo 49',
  },
  {
    id: 'et-5',
    title: 'Estatuto de los Trabajadores',
    category: 'laboral',
    article: 'Artículo 55',
    content: 'El despido disciplinario será calificado como procedente, improcedente o nulo. Será improcedente cuando no se acredite la causa alegada. Será nulo cuando tenga por móvil alguna de las causas de discriminación prohibidas o se produzca en los períodos de suspensión del contrato por maternidad, paternidad, riesgo durante el embarazo o la lactancia.',
    keywords: ['despido', 'improcedente', 'nulo', 'procedente', 'discriminación', 'indemnización'],
    source: 'Estatuto de los Trabajadores, Artículo 55',
  },
  {
    id: 'et-6',
    title: 'Estatuto de los Trabajadores',
    category: 'laboral',
    article: 'Artículo 56',
    content: 'Cuando el despido sea declarado improcedente, el empresario podrá optar entre la readmisión del trabajador o el abono de una indemnización de treinta y tres días de salario por año de servicio, prorrateándose por meses los períodos de tiempo inferiores a un año, hasta un máximo de veinticuatro mensualidades.',
    keywords: ['indemnización despido', 'improcedente', 'readmisión', '33 días', 'año servicio'],
    source: 'Estatuto de los Trabajadores, Artículo 56',
  },
  {
    id: 'lec-1',
    title: 'Ley de Enjuiciamiento Civil',
    category: 'procesal',
    article: 'Artículo 117',
    content: 'La demanda habrá de contener los datos del tribunal, la identificación del demandante y demandado, los hechos en que se funda la pretensión, los fundamentos de derecho y la solicitud concreta de tutela judicial.',
    keywords: ['demanda', 'juicio', 'tribunal', 'pretensión', 'tutela judicial'],
    source: 'Ley de Enjuiciamiento Civil, Artículo 117',
  },
  {
    id: 'lec-2',
    title: 'Ley de Enjuiciamiento Civil',
    category: 'procesal',
    article: 'Artículo 399',
    content: 'El juicio ordinario se iniciará mediante demanda sucinta, a la que se acompañarán los documentos procesales y de fondo pertinentes. El demandado dispondrá de veinte días para contestar a la demanda.',
    keywords: ['juicio ordinario', 'demanda', 'contestación', 'plazo', 'documentos'],
    source: 'Ley de Enjuiciamiento Civil, Artículo 399',
  },
  {
    id: 'lec-3',
    title: 'Ley de Enjuiciamiento Civil',
    category: 'procesal',
    article: 'Artículo 437',
    content: 'El juicio verbal se iniciará mediante demanda sucinta, y se convocará a las partes a la vista en el plazo de diez días. La sentencia se dictará oralmente en el acto de la vista o dentro de los cinco días siguientes.',
    keywords: ['juicio verbal', 'demanda sucinta', 'vista', 'sentencia oral'],
    source: 'Ley de Enjuiciamiento Civil, Artículo 437',
  },
  {
    id: 'lpac-1',
    title: 'Ley del Procedimiento Administrativo Común',
    category: 'administrativo',
    article: 'Artículo 21',
    content: 'La Administración está obligada a dictar resolución expresa en todos los procedimientos y a notificarla. El plazo máximo para resolver será de seis meses, salvo que una norma con rango de ley establezca un plazo mayor o menor.',
    keywords: ['administración', 'procedimiento', 'plazo', 'resolución', 'silencio administrativo'],
    source: 'Ley 39/2015, Artículo 21',
  },
  {
    id: 'lpac-2',
    title: 'Ley del Procedimiento Administrativo Común',
    category: 'administrativo',
    article: 'Artículo 24',
    content: 'Transcurrido el plazo máximo para resolver sin que se haya dictado resolución expresa, se entenderá estimada la solicitud por silencio administrativo positivo, salvo en los supuestos en los que la normativa establezca efectos desestimatorios.',
    keywords: ['silencio administrativo', 'estimación', 'desestimación', 'plazo'],
    source: 'Ley 39/2015, Artículo 24',
  },
  {
    id: 'rgpd-1',
    title: 'Reglamento General de Protección de Datos',
    category: 'proteccion-datos',
    article: 'Artículo 6',
    content: 'El tratamiento de datos personales solo será lícito si el interesado dio su consentimiento, o si es necesario para la ejecución de un contrato, el cumplimiento de una obligación legal, la protección de intereses vitales, el cumplimiento de una misión de interés público o la satisfacción de intereses legítimos del responsable del tratamiento.',
    keywords: ['datos personales', 'consentimiento', 'RGPD', 'privacidad', 'tratamiento datos'],
    source: 'Reglamento UE 2016/679, Artículo 6',
  },
  {
    id: 'rgpd-2',
    title: 'Reglamento General de Protección de Datos',
    category: 'proteccion-datos',
    article: 'Artículo 17',
    content: 'El interesado tendrá derecho a obtener la supresión de sus datos personales cuando ya no sean necesarios para los fines para los que fueron recogidos, retire el consentimiento, se oponga al tratamiento, hayan sido tratados ilícitamente o deban suprimirse por cumplimiento de una obligación legal.',
    keywords: ['supresión datos', 'derecho olvido', 'cancelación', 'RGPD'],
    source: 'Reglamento UE 2016/679, Artículo 17',
  },
  {
    id: 'lopdgdd-1',
    title: 'Ley Orgánica de Protección de Datos y Garantía de Derechos Digitales',
    category: 'proteccion-datos',
    article: 'Artículo 2',
    content: 'La presente ley orgánica tiene por objeto garantizar y proteger los derechos digitales de los ciudadanos conforme al mandato establecido en la Constitución y al Reglamento General de Protección de Datos de la Unión Europea.',
    keywords: ['protección datos', 'derechos digitales', 'LOPDGDD', 'privacidad'],
    source: 'Ley Orgánica 3/2018, Artículo 2',
  },
  {
    id: 'la-1',
    title: 'Ley de Arrendamientos Urbanos',
    category: 'civil',
    article: 'Artículo 9',
    content: 'La duración del arrendamiento será libremente pactada por las partes. Si no supera los cinco años, el arrendatario tendrá derecho a prórrogas anuales obligatorias hasta alcanzar dicho plazo, salvo que manifieste su voluntad de no renovar.',
    keywords: ['alquiler', 'arrendamiento', 'contrato alquiler', 'inquilino', 'prórroga', 'vivienda'],
    source: 'Ley de Arrendamientos Urbanos, Artículo 9',
  },
  {
    id: 'la-2',
    title: 'Ley de Arrendamientos Urbanos',
    category: 'civil',
    article: 'Artículo 36',
    content: 'La fianza en el arrendamiento de vivienda será obligatoria y consistirá en la cantidad equivalente a una mensualidad de renta. Para arrendamientos de uso distinto del de vivienda, la fianza será de dos mensualidades.',
    keywords: ['fianza', 'alquiler', 'depósito', 'mensualidad', 'arrendamiento'],
    source: 'Ley de Arrendamientos Urbanos, Artículo 36',
  },
  {
    id: 'lgs-1',
    title: 'Ley General de la Seguridad Social',
    category: 'laboral',
    article: 'Artículo 152',
    content: 'La pensión de jubilación contributiva se reconocerá a los trabajadores que hayan cumplido la edad ordinaria de jubilación y acrediten un período mínimo de cotización de quince años, de los cuales al menos dos deberán estar comprendidos dentro de los quince años inmediatamente anteriores al hecho causante.',
    keywords: ['jubilación', 'pensión', 'cotización', 'seguridad social', 'edad jubilación'],
    source: 'Ley General de la Seguridad Social, Artículo 152',
  },
  {
    id: 'lgs-2',
    title: 'Ley General de la Seguridad Social',
    category: 'laboral',
    article: 'Artículo 169',
    content: 'En situación de incapacidad temporal, el trabajador tendrá derecho a un subsidio equivalente al 60 por ciento de la base reguladora desde el cuarto día hasta el vigésimo día, y al 75 por ciento desde el día veintiuno en adelante.',
    keywords: ['baja laboral', 'incapacidad temporal', 'subsidio', 'enfermedad', 'base reguladora'],
    source: 'Ley General de la Seguridad Social, Artículo 169',
  },
  {
    id: 'lhcm-1',
    title: 'Ley Hipotecaria',
    category: 'civil',
    article: 'Artículo 1',
    content: 'El Registro de la Propiedad tiene por objeto la inscripción, anotación y cancelación de los actos y contratos relativos al dominio y demás derechos reales sobre bienes inmuebles.',
    keywords: ['hipoteca', 'registro propiedad', 'inmueble', 'vivienda', 'escritura'],
    source: 'Ley Hipotecaria, Artículo 1',
  },
  {
    id: 'lhcm-2',
    title: 'Ley de Contrato de Seguro',
    category: 'civil',
    article: 'Artículo 1',
    content: 'El contrato de seguro es aquél por el que el asegurador se obliga, mediante el cobro de una prima y para el caso de que se produzca el evento cuyo riesgo es objeto de cobertura, a indemnizar el daño producido o a satisfacer un capital, una renta u otras prestaciones convenidas.',
    keywords: ['seguro', 'prima', 'indemnización', 'cobertura', 'siniestro', 'aseguradora'],
    source: 'Ley de Contrato de Seguro, Artículo 1',
  },
];
