from dataclasses import dataclass, field


@dataclass
class LegalDocument:
    id: str
    title: str
    category: str
    article: str
    content: str
    keywords: list
    source: str


SEED_DOCUMENTS: list[LegalDocument] = [
    LegalDocument(
        id="ce-1", title="Constitución Española", category="constitucional",
        article="Artículo 14",
        content="Los españoles son iguales ante la ley, sin que pueda prevalecer discriminación alguna por razón de nacimiento, raza, sexo, religión, opinión o cualquier otra condición o circunstancia personal o social.",
        keywords=["igualdad", "discriminación", "derechos", "igualdad ante la ley"],
        source="Constitución Española, Artículo 14",
    ),
    LegalDocument(
        id="ce-2", title="Constitución Española", category="constitucional",
        article="Artículo 18",
        content="Se garantiza el derecho al honor, a la intimidad personal y familiar y a la propia imagen. El domicilio es inviolable. Ninguna entrada o registro podrá hacerse en él sin consentimiento del titular o resolución judicial, salvo en caso de flagrante delito. Se garantiza el secreto de las comunicaciones y, en especial, de las postales, telegráficas y telefónicas, salvo resolución judicial.",
        keywords=["honor", "intimidad", "domicilio", "inviolabilidad", "secreto comunicaciones", "privacidad"],
        source="Constitución Española, Artículo 18",
    ),
    LegalDocument(
        id="ce-3", title="Constitución Española", category="constitucional",
        article="Artículo 24",
        content="Todas las personas tienen derecho a obtener la tutela efectiva de los jueces y tribunales en el ejercicio de sus derechos e intereses legítimos, sin que, en ningún caso, pueda producirse indefensión. Asimismo, todos tienen derecho al Juez ordinario predeterminado por la ley, a la defensa y a la asistencia de letrado, a ser informados de la acusación formulada contra ellos, a un proceso público sin dilaciones indebidas y con todas las garantías, a utilizar los medios de prueba pertinentes para su defensa, a no declarar contra sí mismos, a no confesarse culpables y a la presunción de inocencia.",
        keywords=["tutela judicial", "defensa", "abogado", "proceso", "presunción inocencia", "juicio"],
        source="Constitución Española, Artículo 24",
    ),
    LegalDocument(
        id="ce-4", title="Constitución Española", category="constitucional",
        article="Artículo 25",
        content="Nadie puede ser condenado o sancionado por acciones u omisiones que en el momento de producirse no constituyan delito, falta o infracción administrativa, según la legislación vigente en aquel momento. Las penas privativas de libertad y las medidas de seguridad estarán orientadas hacia la reeducación y reinserción social.",
        keywords=["pena", "condena", "delito", "sanción", "legalidad penal", "reinserción"],
        source="Constitución Española, Artículo 25",
    ),
    LegalDocument(
        id="ce-5", title="Constitución Española", category="constitucional",
        article="Artículo 33",
        content="Se reconoce el derecho a la propiedad privada y a la herencia. La función social de estos derechos delimitará su contenido, de acuerdo con las leyes. Nadie podrá ser privado de sus bienes y derechos sino por causa justificada de utilidad pública o interés social, mediante la correspondiente indemnización y de conformidad con lo dispuesto por las leyes.",
        keywords=["propiedad", "herencia", "expropiación", "indemnización", "bienes"],
        source="Constitución Española, Artículo 33",
    ),
    LegalDocument(
        id="ce-6", title="Constitución Española", category="constitucional",
        article="Artículo 35",
        content="Todos los españoles tienen el deber de trabajar y el derecho al trabajo, a la libre elección de profesión u oficio, a la promoción a través del trabajo y a una remuneración suficiente para satisfacer sus necesidades y las de su familia, sin que en ningún caso pueda hacerse discriminación por razón de sexo.",
        keywords=["trabajo", "trabajador", "empleo", "salario", "remuneración", "profesión"],
        source="Constitución Española, Artículo 35",
    ),
    LegalDocument(
        id="cc-1", title="Código Civil", category="civil",
        article="Artículo 108",
        content="La obligación se extingue por el pago o cumplimiento, por la pérdida de la cosa debida, por el condonación de la deuda, por la confusión de los derechos de acreedor y deudor, por la compensación y por la novación.",
        keywords=["obligación", "deuda", "pago", "cumplimiento", "contrato"],
        source="Código Civil, Artículo 108",
    ),
    LegalDocument(
        id="cc-2", title="Código Civil", category="civil",
        article="Artículo 109",
        content="El deudor debe cumplir la obligación en los términos en que fue contraída, y es responsable de los daños y perjuicios derivados del incumplimiento, salvo que concurra causa de fuerza mayor.",
        keywords=["deudor", "incumplimiento", "daños", "perjuicios", "responsabilidad contractual"],
        source="Código Civil, Artículo 109",
    ),
    LegalDocument(
        id="cc-3", title="Código Civil", category="civil",
        article="Artículo 1902",
        content="El que por acción u omisión causa daño a otro, interviniendo culpa o negligencia, está obligado a reparar el daño causado.",
        keywords=["responsabilidad civil", "daño", "negligencia", "culpa", "indemnización"],
        source="Código Civil, Artículo 1902",
    ),
    LegalDocument(
        id="cc-4", title="Código Civil", category="civil",
        article="Artículo 1964",
        content="Las acciones personales que no tengan plazo especial prescriben a los cinco años desde que pueda exigirse el cumplimiento de la obligación.",
        keywords=["prescripción", "plazo", "acción personal", "obligación"],
        source="Código Civil, Artículo 1964",
    ),
    LegalDocument(
        id="cp-1", title="Código Penal", category="penal",
        article="Artículo 138",
        content="El que matare a otro será castigado, como reo de homicidio, con la pena de prisión de diez a quince años.",
        keywords=["homicidio", "muerte", "prisión", "pena"],
        source="Código Penal, Artículo 138",
    ),
    LegalDocument(
        id="cp-2", title="Código Penal", category="penal",
        article="Artículo 147",
        content="El que, por cualquier medio o procedimiento, causare a otro una lesión que menoscabe su integridad corporal o su salud física o mental, será castigado con la pena de prisión de tres meses a tres años o multa de seis a doce meses.",
        keywords=["lesiones", "integridad física", "salud", "violencia"],
        source="Código Penal, Artículo 147",
    ),
    LegalDocument(
        id="cp-3", title="Código Penal", category="penal",
        article="Artículo 237",
        content="Son reos del delito de robo los que, con ánimo de lucrarse, se apoderaren de las cosas muebles ajenas empleando fuerza en las cosas para acceder al lugar donde se encuentran o violencia o intimidación en las personas.",
        keywords=["robo", "hurto", "violencia", "intimidación", "apoderamiento"],
        source="Código Penal, Artículo 237",
    ),
    LegalDocument(
        id="cp-4", title="Código Penal", category="penal",
        article="Artículo 248",
        content="Cometen estafa los que, con ánimo de lucro, utilizaren engaño bastante para producir error en otro, induciéndolo a realizar un acto de disposición en perjuicio propio o ajeno.",
        keywords=["estafa", "engaño", "fraude", "lucro"],
        source="Código Penal, Artículo 248",
    ),
    LegalDocument(
        id="et-1", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 4",
        content="Los trabajadores tienen como derechos básicos: trabajo y libre elección de profesión, libre sindicación, negociación colectiva, huelga, reunión, información y formación profesional, no discriminación para el empleo, integridad física y protección frente al acoso.",
        keywords=["trabajador", "derechos laborales", "sindicato", "huelga", "formación"],
        source="Estatuto de los Trabajadores, Artículo 4",
    ),
    LegalDocument(
        id="et-2", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 14",
        content="El período de prueba tendrá una duración máxima de seis meses para los técnicos titulados, y de dos meses para los demás trabajadores, pudiendo establecerse por convenio colectivo duraciones distintas.",
        keywords=["período de prueba", "contrato", "técnico", "trabajador"],
        source="Estatuto de los Trabajadores, Artículo 14",
    ),
    LegalDocument(
        id="et-3", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 33",
        content="El Fondo de Garantía Salarial (FOGASA) abonará a los trabajadores el importe de los salarios pendientes de pago por causa de insolvencia o concurso del empresario, con el límite de 150 días y el doble del SMI.",
        keywords=["FOGASA", "salario", "insolvencia", "concurso", "garantía salarial", "despido"],
        source="Estatuto de los Trabajadores, Artículo 33",
    ),
    LegalDocument(
        id="et-4", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 49",
        content="El contrato de trabajo se extingue por mutuo acuerdo, causas consignadas en el contrato, expiración del tiempo convenido, dimisión del trabajador, muerte del trabajador o empresario, jubilación, despido disciplinario, despido por causas objetivas, despido colectivo y fuerza mayor.",
        keywords=["extinción contrato", "despido", "dimisión", "baja", "fin relación laboral"],
        source="Estatuto de los Trabajadores, Artículo 49",
    ),
    LegalDocument(
        id="et-5", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 55",
        content="El despido disciplinario será calificado como procedente, improcedente o nulo. Será improcedente cuando no se acredite la causa alegada. Será nulo cuando tenga por móvil alguna de las causas de discriminación prohibidas o se produzca en los períodos de suspensión del contrato por maternidad, paternidad, riesgo durante el embarazo o la lactancia.",
        keywords=["despido", "improcedente", "nulo", "procedente", "discriminación", "indemnización"],
        source="Estatuto de los Trabajadores, Artículo 55",
    ),
    LegalDocument(
        id="et-6", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 56",
        content="Cuando el despido sea declarado improcedente, el empresario podrá optar entre la readmisión del trabajador o el abono de una indemnización de treinta y tres días de salario por año de servicio, prorrateándose por meses los períodos de tiempo inferiores a un año, hasta un máximo de veinticuatro mensualidades.",
        keywords=["indemnización despido", "improcedente", "readmisión", "33 días", "año servicio"],
        source="Estatuto de los Trabajadores, Artículo 56",
    ),
    LegalDocument(
        id="lec-1", title="Ley de Enjuiciamiento Civil", category="procesal",
        article="Artículo 117",
        content="La demanda habrá de contener los datos del tribunal, la identificación del demandante y demandado, los hechos en que se funda la pretensión, los fundamentos de derecho y la solicitud concreta de tutela judicial.",
        keywords=["demanda", "juicio", "tribunal", "pretensión", "tutela judicial"],
        source="Ley de Enjuiciamiento Civil, Artículo 117",
    ),
    LegalDocument(
        id="lec-2", title="Ley de Enjuiciamiento Civil", category="procesal",
        article="Artículo 399",
        content="El juicio ordinario se iniciará mediante demanda sucinta, a la que se acompañarán los documentos procesales y de fondo pertinentes. El demandado dispondrá de veinte días para contestar a la demanda.",
        keywords=["juicio ordinario", "demanda", "contestación", "plazo", "documentos"],
        source="Ley de Enjuiciamiento Civil, Artículo 399",
    ),
    LegalDocument(
        id="lec-3", title="Ley de Enjuiciamiento Civil", category="procesal",
        article="Artículo 437",
        content="El juicio verbal se iniciará mediante demanda sucinta, y se convocará a las partes a la vista en el plazo de diez días. La sentencia se dictará oralmente en el acto de la vista o dentro de los cinco días siguientes.",
        keywords=["juicio verbal", "demanda sucinta", "vista", "sentencia oral"],
        source="Ley de Enjuiciamiento Civil, Artículo 437",
    ),
    LegalDocument(
        id="lpac-1", title="Ley del Procedimiento Administrativo Común", category="administrativo",
        article="Artículo 21",
        content="La Administración está obligada a dictar resolución expresa en todos los procedimientos y a notificarla. El plazo máximo para resolver será de seis meses, salvo que una norma con rango de ley establezca un plazo mayor o menor.",
        keywords=["administración", "procedimiento", "plazo", "resolución", "silencio administrativo"],
        source="Ley 39/2015, Artículo 21",
    ),
    LegalDocument(
        id="lpac-2", title="Ley del Procedimiento Administrativo Común", category="administrativo",
        article="Artículo 24",
        content="Transcurrido el plazo máximo para resolver sin que se haya dictado resolución expresa, se entenderá estimada la solicitud por silencio administrativo positivo, salvo en los supuestos en los que la normativa establezca efectos desestimatorios.",
        keywords=["silencio administrativo", "estimación", "desestimación", "plazo"],
        source="Ley 39/2015, Artículo 24",
    ),
    LegalDocument(
        id="rgpd-1", title="Reglamento General de Protección de Datos", category="proteccion-datos",
        article="Artículo 6",
        content="El tratamiento de datos personales solo será lícito si el interesado dio su consentimiento, o si es necesario para la ejecución de un contrato, el cumplimiento de una obligación legal, la protección de intereses vitales, el cumplimiento de una misión de interés público o la satisfacción de intereses legítimos del responsable del tratamiento.",
        keywords=["datos personales", "consentimiento", "RGPD", "privacidad", "tratamiento datos"],
        source="Reglamento UE 2016/679, Artículo 6",
    ),
    LegalDocument(
        id="rgpd-2", title="Reglamento General de Protección de Datos", category="proteccion-datos",
        article="Artículo 17",
        content="El interesado tendrá derecho a obtener la supresión de sus datos personales cuando ya no sean necesarios para los fines para los que fueron recogidos, retire el consentimiento, se oponga al tratamiento, hayan sido tratados ilícitamente o deban suprimirse por cumplimiento de una obligación legal.",
        keywords=["supresión datos", "derecho olvido", "cancelación", "RGPD"],
        source="Reglamento UE 2016/679, Artículo 17",
    ),
    LegalDocument(
        id="lopdgdd-1", title="Ley Orgánica de Protección de Datos y Garantía de Derechos Digitales",
        category="proteccion-datos", article="Artículo 2",
        content="La presente ley orgánica tiene por objeto garantizar y proteger los derechos digitales de los ciudadanos conforme al mandato establecido en la Constitución y al Reglamento General de Protección de Datos de la Unión Europea.",
        keywords=["protección datos", "derechos digitales", "LOPDGDD", "privacidad"],
        source="Ley Orgánica 3/2018, Artículo 2",
    ),
    LegalDocument(
        id="la-1", title="Ley de Arrendamientos Urbanos", category="civil",
        article="Artículo 9",
        content="La duración del arrendamiento será libremente pactada por las partes. Si no supera los cinco años, el arrendatario tendrá derecho a prórrogas anuales obligatorias hasta alcanzar dicho plazo, salvo que manifieste su voluntad de no renovar.",
        keywords=["alquiler", "arrendamiento", "contrato alquiler", "inquilino", "prórroga", "vivienda"],
        source="Ley de Arrendamientos Urbanos, Artículo 9",
    ),
    LegalDocument(
        id="la-2", title="Ley de Arrendamientos Urbanos", category="civil",
        article="Artículo 36",
        content="La fianza en el arrendamiento de vivienda será obligatoria y consistirá en la cantidad equivalente a una mensualidad de renta. Para arrendamientos de uso distinto del de vivienda, la fianza será de dos mensualidades.",
        keywords=["fianza", "alquiler", "depósito", "mensualidad", "arrendamiento"],
        source="Ley de Arrendamientos Urbanos, Artículo 36",
    ),
    LegalDocument(
        id="lgs-1", title="Ley General de la Seguridad Social", category="laboral",
        article="Artículo 152",
        content="La pensión de jubilación contributiva se reconocerá a los trabajadores que hayan cumplido la edad ordinaria de jubilación y acrediten un período mínimo de cotización de quince años, de los cuales al menos dos deberán estar comprendidos dentro de los quince años inmediatamente anteriores al hecho causante.",
        keywords=["jubilación", "pensión", "cotización", "seguridad social", "edad jubilación"],
        source="Ley General de la Seguridad Social, Artículo 152",
    ),
    LegalDocument(
        id="lgs-2", title="Ley General de la Seguridad Social", category="laboral",
        article="Artículo 169",
        content="En situación de incapacidad temporal, el trabajador tendrá derecho a un subsidio equivalente al 60 por ciento de la base reguladora desde el cuarto día hasta el vigésimo día, y al 75 por ciento desde el día veintiuno en adelante.",
        keywords=["baja laboral", "incapacidad temporal", "subsidio", "enfermedad", "base reguladora"],
        source="Ley General de la Seguridad Social, Artículo 169",
    ),
    LegalDocument(
        id="lhcm-1", title="Ley Hipotecaria", category="civil",
        article="Artículo 1",
        content="El Registro de la Propiedad tiene por objeto la inscripción, anotación y cancelación de los actos y contratos relativos al dominio y demás derechos reales sobre bienes inmuebles.",
        keywords=["hipoteca", "registro propiedad", "inmueble", "vivienda", "escritura"],
        source="Ley Hipotecaria, Artículo 1",
    ),
    LegalDocument(
        id="lhcm-2", title="Ley de Contrato de Seguro", category="civil",
        article="Artículo 1",
        content="El contrato de seguro es aquél por el que el asegurador se obliga, mediante el cobro de una prima y para el caso de que se produzca el evento cuyo riesgo es objeto de cobertura, a indemnizar el daño producido o a satisfacer un capital, una renta u otras prestaciones convenidas.",
        keywords=["seguro", "prima", "indemnización", "cobertura", "siniestro", "aseguradora"],
        source="Ley de Contrato de Seguro, Artículo 1",
    ),

    # ===== CONSTITUCIONAL (ampliación) =====
    LegalDocument(
        id="ce-7", title="Constitución Española", category="constitucional",
        article="Artículo 15",
        content="Todos tienen derecho a la vida y a la integridad física y moral, sin que, en ningún caso, puedan ser sometidos a tortura ni a penas o tratos inhumanos o degradantes. Queda abolida la pena de muerte, salvo lo que puedan disponer las leyes penales militares para tiempos de guerra.",
        keywords=["vida", "integridad física", "tortura", "pena muerte", "derechos fundamentales"],
        source="Constitución Española, Artículo 15",
    ),
    LegalDocument(
        id="ce-8", title="Constitución Española", category="constitucional",
        article="Artículo 17",
        content="Toda persona tiene derecho a la libertad y a la seguridad. Nadie puede ser privado de su libertad sino con la observancia de lo establecido en este artículo y en los casos y en la forma previstos en la ley. La detención preventiva no podrá durar más del tiempo estrictamente necesario para la realización de las averiguaciones tendentes al esclarecimiento de los hechos, y en todo caso, en el plazo máximo de setenta y dos horas, el detenido deberá ser puesto en libertad o a disposición de la autoridad judicial.",
        keywords=["libertad", "detención", "seguridad", "habeas corpus", "plazo detención"],
        source="Constitución Española, Artículo 17",
    ),
    LegalDocument(
        id="ce-9", title="Constitución Española", category="constitucional",
        article="Artículo 27",
        content="Todos tienen el derecho a la educación. Se reconoce la libertad de enseñanza. La educación tendrá por objeto el pleno desarrollo de la personalidad humana en el respeto a los principios democráticos de convivencia y a los derechos y libertades fundamentales. La enseñanza básica es obligatoria y gratuita.",
        keywords=["educación", "enseñanza", "colegio", "formación", "libertad enseñanza"],
        source="Constitución Española, Artículo 27",
    ),
    LegalDocument(
        id="ce-10", title="Constitución Española", category="constitucional",
        article="Artículo 43",
        content="Se reconoce el derecho a la protección de la salud. Compete a los poderes públicos organizar y tutelar la salud pública a través de medidas preventivas y de las prestaciones y servicios necesarios. La ley establecerá los derechos y deberes de todos al respecto.",
        keywords=["salud", "sanidad", "protección salud", "asistencia sanitaria", "pública"],
        source="Constitución Española, Artículo 43",
    ),
    LegalDocument(
        id="ce-11", title="Constitución Española", category="constitucional",
        article="Artículo 9",
        content="Los ciudadanos y los poderes públicos están sujetos a la Constitución y al resto del ordenamiento jurídico. Corresponde a los poderes públicos promover las condiciones para que la libertad y la igualdad del individuo y de los grupos en que se integra sean reales y efectivas; remover los obstáculos que impidan o dificulten su plenitud y facilitar la participación de todos los ciudadanos en la vida política, económica, cultural y social.",
        keywords=["legalidad", "igualdad real", "participación", "poderes públicos", "constitución"],
        source="Constitución Española, Artículo 9",
    ),

    # ===== CIVIL (ampliación) =====
    LegalDocument(
        id="cc-5", title="Código Civil", category="civil",
        article="Artículo 1254",
        content="El contrato existe desde que una o varias personas consienten en obligarse, respecto de otra u otras, a dar alguna cosa o prestar algún servicio.",
        keywords=["contrato", "consentimiento", "obligación", "acuerdo", "prestación"],
        source="Código Civil, Artículo 1254",
    ),
    LegalDocument(
        id="cc-6", title="Código Civil", category="civil",
        article="Artículo 1255",
        content="Los contratantes pueden establecer los pactos, cláusulas y condiciones que tengan por conveniente, siempre que no sean contrarios a las leyes, a la moral ni al orden público.",
        keywords=["contrato", "libertad contractual", "pactos", "cláusulas", "autonomía voluntad"],
        source="Código Civil, Artículo 1255",
    ),
    LegalDocument(
        id="cc-7", title="Código Civil", category="civil",
        article="Artículo 1281",
        content="Si los términos de un contrato son claros y no dejan duda sobre la intención de los contratantes, se estará al sentido literal de sus cláusulas. Si las palabras parecieren contrarias a la intención evidente de los contratantes, prevalecerá ésta sobre aquéllas.",
        keywords=["contrato", "interpretación", "cláusulas", "literal", "intención"],
        source="Código Civil, Artículo 1281",
    ),
    LegalDocument(
        id="cc-8", title="Código Civil", category="civil",
        article="Artículo 1461",
        content="El vendedor está obligado a la entrega y saneamiento de la cosa objeto de la venta.",
        keywords=["compraventa", "vendedor", "entrega", "saneamiento", "obligación"],
        source="Código Civil, Artículo 1461",
    ),
    LegalDocument(
        id="cc-9", title="Código Civil", category="civil",
        article="Artículo 348",
        content="La propiedad es el derecho de gozar y disponer de una cosa, sin más limitaciones que las establecidas en las leyes. El propietario tiene acción contra el tenedor y el poseedor de la cosa para reivindicarla.",
        keywords=["propiedad", "dominio", "reivindicación", "posesión", "derecho real"],
        source="Código Civil, Artículo 348",
    ),
    LegalDocument(
        id="cc-10", title="Código Civil", category="civil",
        article="Artículo 1540",
        content="El arrendamiento es un contrato por el cual una de las partes se obliga a dar a la otra el goce o uso de una cosa por tiempo determinado y precio cierto.",
        keywords=["arrendamiento", "alquiler", "uso", "precio", "contrato"],
        source="Código Civil, Artículo 1540",
    ),
    LegalDocument(
        id="la-3", title="Ley de Arrendamientos Urbanos", category="civil",
        article="Artículo 21",
        content="La renta podrá ser actualizada anualmente por el arrendador o el arrendatario en la cuantía que resulte de la variación del Índice de Precios de Consumo (IPC) publicado por el Instituto Nacional de Estadística. Las partes podrán pactar un índice de referencia distinto.",
        keywords=["alquiler", "renta", "IPC", "actualización", "subida", "arrendamiento"],
        source="Ley de Arrendamientos Urbanos, Artículo 21",
    ),
    LegalDocument(
        id="lph-1", title="Ley de Propiedad Horizontal", category="civil",
        article="Artículo 3",
        content="La propiedad horizontal se rige por el título constitutivo de la misma y por los estatutos, y en lo no previsto por esta Ley. El título constitutivo describirá el edificio y las viviendas o locales en que se divide, asignando a cada uno una cuota de participación con referencia al total del valor del inmueble.",
        keywords=["comunidad vecinos", "propiedad horizontal", "derramas", "piso", "comunidad"],
        source="Ley de Propiedad Horizontal, Artículo 3",
    ),
    LegalDocument(
        id="lph-2", title="Ley de Propiedad Horizontal", category="civil",
        article="Artículo 9",
        content="Son obligaciones de cada propietario: contribuir a los gastos generales según su cuota de participación, mantener su vivienda en buen estado, consentir las reparaciones necesarias, y permitir la entrada para reparaciones urgentes. El impago de gastos comunes dará lugar a reclamación judicial.",
        keywords=["comunidad", "gastos", "derramas", "impago", "vecinos", "obligaciones"],
        source="Ley de Propiedad Horizontal, Artículo 9",
    ),
    LegalDocument(
        id="lph-3", title="Ley de Propiedad Horizontal", category="civil",
        article="Artículo 7",
        content="Al propietario de cada piso o local no le está permitido desarrollar en el mismo actividades prohibidas en los estatutos, que resulten dañosas para la finca o que contravengan las disposiciones generales sobre actividades molestas, insalubres, nocivas, peligrosas o ilícitas. El Presidente de la comunidad podrá requerir al propietario el cese inmediato de dichas actividades.",
        keywords=["comunidad", "actividades molestas", "ruido", "vecinos", "reclamación"],
        source="Ley de Propiedad Horizontal, Artículo 7",
    ),

    # ===== PENAL (ampliación) =====
    LegalDocument(
        id="cp-5", title="Código Penal", category="penal",
        article="Artículo 234",
        content="El que, con ánimo de lucro, tomare las cosas muebles ajenas sin la voluntad de su dueño será castigado, como reo de hurto, con la pena de prisión de seis a dieciocho meses si la cuantía de lo sustraído superase los 400 euros.",
        keywords=["hurto", "robo", "sustracción", "pena", "lucro"],
        source="Código Penal, Artículo 234",
    ),
    LegalDocument(
        id="cp-6", title="Código Penal", category="penal",
        article="Artículo 153",
        content="El que por cualquier medio o procedimiento causare a otro un menoscabo psíquico o una lesión de menor gravedad de las previstas en el artículo 147, o golpeare o maltratare de obra a otro sin causarle lesión, cuando la víctima sea o haya sido su cónyuge o persona que esté o haya estado ligada a él por una análoga relación de afectividad, será castigado con la pena de prisión de seis meses a un año o trabajos en beneficio de la comunidad.",
        keywords=["violencia género", "maltrato", "mujer", "pareja", "lesiones", "violencia doméstica"],
        source="Código Penal, Artículo 153",
    ),
    LegalDocument(
        id="cp-7", title="Código Penal", category="penal",
        article="Artículo 205",
        content="La calumnia es la imputación de un delito hecha con conocimiento de su falsedad o temerario desprecio hacia la verdad. Las injurias son las expresiones o acciones que lesionan la dignidad de otra persona, menoscabando su fama o atentando contra su propia estimación.",
        keywords=["calumnia", "injurias", "difamación", "honor", "falsedad"],
        source="Código Penal, Artículo 205",
    ),
    LegalDocument(
        id="cp-8", title="Código Penal", category="penal",
        article="Artículo 305",
        content="El que por acción u omisión defraude a la Hacienda Pública estatal, autonómica, foral o local, siempre que la cuantía defraudada exceda de 120.000 euros, será castigado con la pena de prisión de uno a cinco años y multa del tanto al séxtuplo de la cuantía defraudada.",
        keywords=["delito fiscal", "hacienda", "fraude", "impuestos", "defraudación"],
        source="Código Penal, Artículo 305",
    ),

    # ===== LABORAL (ampliación) =====
    LegalDocument(
        id="et-7", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 15",
        content="El contrato de trabajo se presume concertado por tiempo indefinido. El contrato de duración determinada solo podrá celebrarse por circunstancias de la producción o por sustitución de persona trabajadora. La duración máxima del contrato por circunstancias de la producción será de seis meses, ampliable hasta doce meses por convenio colectivo.",
        keywords=["contrato temporal", "duración determinada", "temporalidad", "indefinido", "eventual"],
        source="Estatuto de los Trabajadores, Artículo 15",
    ),
    LegalDocument(
        id="et-8", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 34",
        content="La duración de la jornada de trabajo será la pactada en los convenios colectivos o contratos, sin que pueda exceder de cuarenta horas semanales de trabajo efectivo de promedio en cómputo anual. El trabajador tendrá derecho a un descanso mínimo de doce horas entre el final de una jornada y el comienzo de la siguiente.",
        keywords=["jornada laboral", "horas", "descanso", "horario", "40 horas"],
        source="Estatuto de los Trabajadores, Artículo 34",
    ),
    LegalDocument(
        id="et-9", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 37",
        content="Los trabajadores tendrán derecho a un descanso semanal mínimo de día y medio ininterrumpido, acumulable por períodos de hasta catorce días. Asimismo, tendrán derecho a catorce festivos al año, de los cuales dos serán locales. El descanso semanal y los festivos serán retribuidos.",
        keywords=["descanso semanal", "festivos", "vacaciones", "días libres", "retribuido"],
        source="Estatuto de los Trabajadores, Artículo 37",
    ),
    LegalDocument(
        id="et-10", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 40",
        content="El traslado de un trabajador a un centro de trabajo distinto de la misma empresa que exija cambio de residencia requerirá la apertura de un período de consultas con los representantes legales de los trabajadores. El trabajador tendrá derecho a optar entre el traslado o la extinción de su contrato, percibiendo una indemnización de veinte días de salario por año de servicio.",
        keywords=["traslado", "movilidad geográfica", "cambio residencia", "indemnización", "despido"],
        source="Estatuto de los Trabajadores, Artículo 40",
    ),
    LegalDocument(
        id="et-11", title="Estatuto de los Trabajadores", category="laboral",
        article="Artículo 54",
        content="El despido disciplinario podrá basarse en incumplimientos contractuales graves y culpables del trabajador, como las faltas repetidas e injustificadas de asistencia o puntualidad, la indisciplina o desobediencia, las ofensas verbales o físicas, la transgresión de la buena fe contractual, la disminución continuada y voluntaria del rendimiento y la embriaguez o toxicomanía habitual que repercuta negativamente en el trabajo.",
        keywords=["despido disciplinario", "causas", "incumplimiento", "sanción", "falta"],
        source="Estatuto de los Trabajadores, Artículo 54",
    ),

    # ===== PROCESAL (ampliación) =====
    LegalDocument(
        id="lec-4", title="Ley de Enjuiciamiento Civil", category="procesal",
        article="Artículo 216",
        content="Los tribunales civiles decidirán los asuntos en virtud de las aportaciones de hechos, pruebas y pretensiones de las partes, excepto cuando la ley disponga otra cosa en casos especiales. Este principio se conoce como principio de justicia rogada.",
        keywords=["justicia rogada", "tribunal", "partes", "proceso", "principio dispositivo"],
        source="Ley de Enjuiciamiento Civil, Artículo 216",
    ),
    LegalDocument(
        id="lec-5", title="Ley de Enjuiciamiento Civil", category="procesal",
        article="Artículo 247",
        content="Todos los intervinientes en un proceso civil deberán actuar conforme a las reglas de la buena fe. El tribunal podrá rechazar motivadamente las peticiones e incidentes que se formulen con manifiesto abuso de derecho o entrañen fraude de ley o procesal.",
        keywords=["buena fe", "abuso derecho", "fraude procesal", "proceso", "lealtad"],
        source="Ley de Enjuiciamiento Civil, Artículo 247",
    ),
    LegalDocument(
        id="lecrim-1", title="Ley de Enjuiciamiento Criminal", category="procesal",
        article="Artículo 118",
        content="Toda persona a quien se impute un acto punible podrá ejercitar el derecho de defensa, actuando en el procedimiento cualquiera que sea su estado, desde que se le comunique su existencia, se le haya detenido o se haya acordado su detención. Se le informará de los hechos que se le imputan y de sus derechos, y podrá designar abogado de su confianza o solicitar que se le nombre de oficio.",
        keywords=["defensa", "abogado", "imputado", "derechos", "detenido", "asistencia letrada"],
        source="Ley de Enjuiciamiento Criminal, Artículo 118",
    ),
    LegalDocument(
        id="lecrim-2", title="Ley de Enjuiciamiento Criminal", category="procesal",
        article="Artículo 505",
        content="La prisión provisional solo podrá ser acordada cuando existan motivos para creer responsable criminalmente del delito a la persona investigada y concurra alguna de las siguientes circunstancias: riesgo de fuga, riesgo de destrucción de pruebas, riesgo de que el investigado cometa nuevos delitos, o riesgo de que pueda atentar contra la víctima.",
        keywords=["prisión provisional", "cárcel", "fianza", "libertad", "medida cautelar"],
        source="Ley de Enjuiciamiento Criminal, Artículo 505",
    ),

    # ===== ADMINISTRATIVO (ampliación) =====
    LegalDocument(
        id="lpac-3", title="Ley del Procedimiento Administrativo Común", category="administrativo",
        article="Artículo 53",
        content="Los interesados en el procedimiento administrativo tienen derecho a: conocer el estado de la tramitación, acceder al expediente, formular alegaciones, proponer pruebas, no presentar documentos no exigidos por la normativa, y ser informados del plazo máximo para resolver y de los efectos del silencio administrativo.",
        keywords=["interesado", "derechos", "procedimiento", "alegaciones", "expediente", "administración"],
        source="Ley 39/2015, Artículo 53",
    ),
    LegalDocument(
        id="lpac-4", title="Ley del Procedimiento Administrativo Común", category="administrativo",
        article="Artículo 35",
        content="Los ciudadanos tienen derecho a obtener información y orientación acerca de los requisitos jurídicos o técnicos que las disposiciones vigentes impongan a los proyectos, actuaciones o solicitudes que se propongan realizar. También tienen derecho a ser asistidos en la cumplimentación de solicitudes y documentos administrativos.",
        keywords=["información", "orientación", "ciudadano", "administración", "asistencia"],
        source="Ley 39/2015, Artículo 35",
    ),
    LegalDocument(
        id="ljca-1", title="Ley de la Jurisdicción Contencioso-Administrativa", category="administrativo",
        article="Artículo 1",
        content="Los Juzgados y Tribunales del orden contencioso-administrativo conocerán de las pretensiones que se deduzcan en relación con la actuación de las Administraciones públicas sujeta al Derecho Administrativo. También conocerán de los recursos contra el silencio administrativo y la inactividad de la Administración.",
        keywords=["contencioso", "administración", "recurso", "tribunal", "silencio administrativo"],
        source="LJCA, Artículo 1",
    ),

    # ===== PROTECCIÓN DATOS (ampliación) =====
    LegalDocument(
        id="rgpd-3", title="Reglamento General de Protección de Datos", category="proteccion-datos",
        article="Artículo 5",
        content="Los datos personales serán: tratados de manera lícita, leal y transparente; recogidos con fines determinados, explícitos y legítimos; adecuados, pertinentes y limitados a lo necesario; exactos y actualizados; mantenidos de forma que se permita la identificación durante no más tiempo del necesario; y tratados de forma segura.",
        keywords=["principios", "datos", "protección", "licitud", "transparencia", "RGPD"],
        source="Reglamento UE 2016/679, Artículo 5",
    ),
    LegalDocument(
        id="rgpd-4", title="Reglamento General de Protección de Datos", category="proteccion-datos",
        article="Artículo 13",
        content="Cuando se recojan datos personales, el responsable del tratamiento deberá facilitar al interesado: la identidad del responsable, los fines del tratamiento, la base legal, los destinatarios de los datos, el plazo de conservación, la existencia de los derechos ARSULIPO (acceso, rectificación, supresión, limitación, portabilidad, oposición), y el derecho a retirar el consentimiento en cualquier momento.",
        keywords=["información", "datos", "consentimiento", "ARSULIPO", "derechos", "RGPD"],
        source="Reglamento UE 2016/679, Artículo 13",
    ),
    LegalDocument(
        id="lopdgdd-2", title="Ley Orgánica de Protección de Datos", category="proteccion-datos",
        article="Artículo 6",
        content="El tratamiento de datos personales basado en el cumplimiento de una obligación legal exigible al responsable del tratamiento será lícito cuando así lo establezca una norma de derecho de la Unión Europea o una norma con rango de ley, que podrá determinar las condiciones generales del tratamiento y los tipos de datos objeto del mismo.",
        keywords=["obligación legal", "datos", "tratamiento", "licitud", "LOPDGDD"],
        source="Ley Orgánica 3/2018, Artículo 6",
    ),

    # ===== CONSUMIDOR (nueva categoría) =====
    LegalDocument(
        id="trlgdcu-1", title="Texto Refundido Ley General Consumidores", category="consumidor",
        article="Artículo 8",
        content="Son derechos básicos de los consumidores y usuarios: la protección contra riesgos que puedan afectar su salud o seguridad; la protección de sus legítimos intereses económicos; la indemnización o reparación de los daños sufridos; la información correcta sobre los productos o servicios; la educación en materia de consumo; la audiencia en consulta y la participación en procedimientos que les afecten.",
        keywords=["consumidor", "usuario", "derechos", "garantía", "devolución", "compra"],
        source="TRLGDCU, Artículo 8",
    ),
    LegalDocument(
        id="trlgdcu-2", title="Texto Refundido Ley General Consumidores", category="consumidor",
        article="Artículo 114",
        content="El consumidor y usuario tiene derecho a la reparación o sustitución del producto cuando este no sea conforme con el contrato de compraventa, salvo que una de estas opciones resulte imposible o desproporcionada. El vendedor responderá de las faltas de conformidad que se manifiesten en un plazo de dos años desde la entrega.",
        keywords=["garantía", "producto", "defecto", "reparación", "sustitución", "devolución"],
        source="TRLGDCU, Artículo 114",
    ),
    LegalDocument(
        id="trlgdcu-3", title="Texto Refundido Ley General Consumidores", category="consumidor",
        article="Artículo 83",
        content="Serán nulas de pleno derecho y se tendrán por no puestas las cláusulas abusivas en los contratos celebrados con consumidores y usuarios. Se consideran cláusulas abusivas todas aquellas que, en contra de las exigencias de la buena fe, causen, en perjuicio del consumidor, un desequilibrio importante de los derechos y obligaciones de las partes.",
        keywords=["cláusulas abusivas", "consumidor", "nulo", "contrato", "condiciones generales"],
        source="TRLGDCU, Artículo 83",
    ),

    # ===== TRÁFICO (nueva categoría) =====
    LegalDocument(
        id="trafico-1", title="Ley de Tráfico y Seguridad Vial", category="trafico",
        article="Artículo 77",
        content="Las infracciones a las normas de circulación se clasifican en leves, graves y muy graves. Son infracciones graves, entre otras: conducir con tasas de alcohol superiores a las permitidas, superar los límites de velocidad en más de 30 km/h, conducir sin permiso, y no someterse a las pruebas de alcohol y drogas. Las multas por infracciones graves pueden alcanzar los 500 euros.",
        keywords=["multa", "tráfico", "alcohol", "velocidad", "sanción", "carnet", "puntos"],
        source="Ley de Tráfico y Seguridad Vial, Artículo 77",
    ),
    LegalDocument(
        id="trafico-2", title="Ley de Tráfico y Seguridad Vial", category="trafico",
        article="Artículo 47",
        content="El permiso de conducción por puntos se regirá por las siguientes reglas: todo conductor dispone de un saldo inicial de 12 puntos; la comisión de infracciones graves o muy graves conlleva la pérdida de entre 2 y 6 puntos; cuando se pierda la totalidad de los puntos, el conductor deberá realizar un curso de sensibilización y superar una prueba para recuperar el permiso.",
        keywords=["puntos", "carnet", "permiso conducir", "infracción", "curso", "recuperación"],
        source="Ley de Tráfico y Seguridad Vial, Artículo 47",
    ),
    LegalDocument(
        id="trafico-3", title="Ley de Tráfico y Seguridad Vial", category="trafico",
        article="Artículo 59",
        content="En caso de accidente de tráfico, los conductores implicados deberán: detenerse sin obstaculizar la circulación, permanecer en el lugar hasta que lleguen los agentes, auxiliar a los heridos si los hubiera, y facilitar sus datos a los demás afectados. El incumplimiento de estas obligaciones puede constituir un delito de abandono del lugar del accidente.",
        keywords=["accidente", "tráfico", "auxilio", "parte", "seguro", "abandono"],
        source="Ley de Tráfico y Seguridad Vial, Artículo 59",
    ),
]
